### ISSUE TITLE
提示微信未运行

### ISSUE THREAD

**Issue by Shawn-Jones-7** [raffeyang/wechat#12]
![WechatIMG707](https://github.com/raffeyang/wechat/assets/134922845/bac05f1a-ea7c-40b3-b4f7-044f702b05bb)
[WeChatTweak-macOS]已安装，微信也开着呢，麻烦检查下是我哪里出错了，谢谢

**Comment by raffeyang** [comment]
1、安装[微信](https://www.wechat.com)
2、请按照这里的方法安装[WeChatTweak](https://github.com/Sunnyyoung/WeChatTweak-macOS)
3、Raycast输入wechat运行
