### ISSUE TITLE
hxd，微信啥时候能上架商店？

### ISSUE THREAD

**Issue by Lawrence-of-AnKing** [raffeyang/wechat#2]
我现在用的还是本地安装的方式，不知道你是否已经提交了拓展。🤔

**Comment by raffeyang** [comment]
之前有bug，不方便上架，已修复全部bug，周末会提交，之前提交过其他插件，估计一周左右正式审核过。

**Comment by raffeyang** [comment]
已经提交到Raycast Store，正在审核https://github.com/raycast/extensions/pull/3844

**Comment by raffeyang** [comment]
已上架
<p align="center">
<a href="https://www.raycast.com/raffeyang/wechat"><img src="https://www.raycast.com/raffeyang/wechat/install_button@2x.png" height="64" style="height: 64px;" alt=""></a>
</p>

**Comment by raffeyang** [comment]
审核通过，可以使用商店版本了
https://www.raycast.com/raffeyang/wechat
