### ISSUE TITLE
每次搜索后，短时间内打开Raycast会出现 SocketError: closed 错误

### ISSUE THREAD

**Issue by Lawrence-of-AnKing** [raffeyang/wechat#3]
如图：
![2022-12-07-094554](https://cdn.jsdelivr.net/gh/Lawrence-of-AnKing/ImgBank@main/MdImg/2022/12/2022-12-07-094554.png)
当Raycast设置成执行命令后不立即退出（为了方便有时候需要回顾）时，执行搜索并跳转联系人后，就会出现这种警告。

**Comment by raffeyang** [comment]
已修复全部bug，周末会提交，之前提交过其他插件，估计一周左右正式审核过。

**Comment by raffeyang** [comment]
新版本可以测试看看，修复了之前的报错，增加了是否按照微信检测
