### ISSUE TITLE
即使已经安装WeChatTweak，仍然提示未安装

### ISSUE THREAD

**Issue by Lawrence-of-AnKing** [raffeyang/wechat#4]
如图，即使已经安装WeChatTweak，仍然提示未安装，**但还是可以搜索**：

![2022-12-18-184552](https://cdn.jsdelivr.net/gh/Lawrence-of-AnKing/ImgBank@main/MdImg/2022/12/2022-12-18-184552.png)

如图，已经安装：

![2022-12-11-105138](https://cdn.jsdelivr.net/gh/Lawrence-of-AnKing/ImgBank@main/MdImg/2022/12/2022-12-11-105138.png)

**Comment by raffeyang** [comment]
请使用WeChatExtension作者提供的方法方法安装，是不会有问题的
```zsh
brew install sunnyyoung/repo/wechattweak-cli
```

```zsh
sudo wechattweak-cli install 
```

**Comment by Lawrence-of-AnKing** [comment]
> 请使用WeChatTweak作者提供的方法方法安装，是不会有问题的
> 
> ```shell
> brew install sunnyyoung/repo/wechattweak-cli
> ```
> 
> ```shell
> sudo wechattweak-cli install 
> ```
> 
> 检测是否安装可以输入
> 
> ```shell
> which wechattweak-cli
> ```
> 
> 正常路径应该是`/usr/local/bin/wechattweak-cli`

我很确定我安装了——通过brew的方式，不过我的路径并不是 `/usr/local/bin/wechattweak-cli` ，而是 `/opt/homebrew/bin/wechattweak-cli` ，实际上搜索插件可以正常使用，只是它会提示你没有安装wechat tweak。

我想，是否可以加入一个选项，让用户来选择 wechat tweak 的安装位置？

或者，把这两个路径都加入其中。

安装路径如下：

<img width="697" alt="image" src="https://user-images.githubusercontent.com/22313057/206895215-f593af80-d29a-4dc5-8b14-47d0e842abac.png">

实测可以使用，但是提示未安装 wechat tweak：

<img width="886" alt="image" src="https://user-images.githubusercontent.com/22313057/206895254-f55936d1-4bb1-42ce-8569-32fe10365f15.png">

**Comment by Lawrence-of-AnKing** [comment]
> 请使用WeChatTweak作者提供的方法方法安装，是不会有问题的
> 
> ```shell
> brew install sunnyyoung/repo/wechattweak-cli
> ```
> 
> ```shell
> sudo wechattweak-cli install 
> ```
> 
> 检测是否安装可以输入
> 
> ```shell
> which wechattweak-cli
> ```
> 
> 正常路径应该是`/usr/local/bin/wechattweak-cli`

在我将 `~/wechat-main/src/util/isWeChatTweakInstalled.tsx` 这个文件中的路径，从 `/usr/local/bin/wechattweak-cli` 改到 `/opt/homebrew/bin/wechattweak-cli` 后，插件一切工作正常。

**Comment by raffeyang** [comment]
增加了其他路径

**Comment by Lawrence-of-AnKing** [comment]
> 增加了其他路径

问题依旧：

![2022-12-18-184138](https://cdn.jsdelivr.net/gh/Lawrence-of-AnKing/ImgBank@main/MdImg/2022/12/2022-12-18-184138.png)

虽然可以正常使用，但是还是弹窗提示未安装WeChatTweak-CLI。

**Comment by raffeyang** [comment]
clone最新的代码，输入，测试是否正常，如果正常我会更新一下商店版本
`npm install`
`npx ray develop`

**Comment by raffeyang** [comment]
商店版本审核通过之前，可以先用这里的方法使用最新版
https://github.com/raffeyang/wechat/releases/tag/Raycast

**Comment by raffeyang** [comment]
审核通过，可以使用商店版本了
https://www.raycast.com/raffeyang/wechat
