### ISSUE TITLE
提示未安装 tweak

### ISSUE THREAD

**Issue by wangkunlin** [raffeyang/wechat#5]
![image](https://user-images.githubusercontent.com/8307768/212875946-2cd9dad2-ca83-4399-919b-8a005166204e.png)
提示未安装 tweak

**Comment by wangkunlin** [comment]
![image](https://user-images.githubusercontent.com/8307768/212876148-db3b77b2-45e9-4d14-8f49-a1fd9f93dd30.png)
系统信息

**Comment by wangkunlin** [comment]
![image](https://user-images.githubusercontent.com/8307768/212883850-d1b1fd03-353f-4cee-8ff2-6b947f8c8c97.png)
看了你下你的代码，是路径写死了，是否可以改为  which 命令来判断呢

**Comment by raffeyang** [comment]
> ![image](https://user-images.githubusercontent.com/8307768/212883850-d1b1fd03-353f-4cee-8ff2-6b947f8c8c97.png)
> 看了你下你的代码，是路径写死了，是否可以改为 which 命令来判断呢

请使用标准方式安装，不会有问题，你的这个情况是brew没有安装到标准目录，brew安装的应该在`/usr/local`下面

**Comment by wangkunlin** [comment]
就是用 ```brew install sunnyyoung/repo/wechattweak-cli``` 这个命令安装的，我不是手动安装的

**Comment by raffeyang** [comment]
> 就是用 `brew install sunnyyoung/repo/wechattweak-cli` 这个命令安装的，我不是手动安装的

卸载开发版，试试商店版本
<p align="center">
<a href="https://www.raycast.com/raffeyang/wechat"><img src="https://www.raycast.com/raffeyang/wechat/install_button@2x.png" height="64" style="height: 64px;" alt=""></a>
</p>

**Comment by Leeiio** [comment]
商店版还是存在问题

**Comment by wangkunlin** [comment]
@raffeyang 商店还没更新
![image](https://user-images.githubusercontent.com/8307768/213064297-f0050a51-ab11-4c53-b537-201bac114b6e.png)

**Comment by raffeyang** [comment]
clone最新的代码，输入，测试是否正常，如果正常我会更新一下商店版本
`npm install`
`npx ray develop`

**Comment by raffeyang** [comment]
> > clone最新的代码，输入，测试是否正常，如果正常我会更新一下商店版本 `npm install` `npx ray develop`
> 
> 我这里没有 npm 环境，不太想安装

打开Raycast 输入Import Extension选择根目录即可测试

**Comment by wangkunlin** [comment]
> > > clone最新的代码，输入，测试是否正常，如果正常我会更新一下商店版本 `npm install` `npx ray develop`
> > 
> > 
> > 我这里没有 npm 环境，不太想安装
> 
> 打开Raycast 输入Import Extension选择根目录即可测试

直接 import 不行，报错

**Comment by wangkunlin** [comment]
![image](https://user-images.githubusercontent.com/8307768/213107342-379468a1-ca06-4dff-952c-e31f24f020c1.png)

**Comment by wangkunlin** [comment]
> clone最新的代码，输入，测试是否正常，如果正常我会更新一下商店版本 `npm install` `npx ray develop`

安装了 npm，测试了，可以正常使用

**Comment by raffeyang** [comment]
下载.zip文件，解压，然后Import Extension
[wechat.zip](https://github.com/raffeyang/wechat/files/10443195/wechat.zip)

**Comment by wangkunlin** [comment]
> 下载.zip文件，解压，然后Import Extension [wechat.zip](https://github.com/raffeyang/wechat/files/10443195/wechat.zip)

我刚才安装了 npm，测试可以正常使用

**Comment by raffeyang** [comment]
商店版本审核通过之前，可以先用这里的方法使用最新版
https://github.com/raffeyang/wechat/releases/tag/Raycast

**Comment by raffeyang** [comment]
审核通过，可以使用商店版本了
https://www.raycast.com/raffeyang/wechat
