### ISSUE TITLE
安装之后，无法识别WeChatTweak

### ISSUE THREAD

**Issue by nscmiaoxin** [raffeyang/wechat#6]
按照流程安装了WeChatTweak、Raycast的WeChat插件，但是在进入插件之后，依旧一直提示没有安装WeChatTweak的弹窗，希望修复

**Comment by wangkunlin** [comment]
我修改了一下 ```~/.config/raycast/extensions/cafe5af0-e733-4989-b9f1-4424f66f25bf/index.js``` 下的 插件代码(插件id的值不确定所有人都一样，需要自己确认)，把 路径 判断给给成我的了，通过 ```which wechattweak-cli``` 命令确认自己的 tweak 路径，我的路径是 /opt/homebrew/bin/wechattweak-cli
```
la.existsSync("/usr/local/bin/wechattweak-cli")
// 从上面改成下面
la.existsSync("/opt/homebrew/bin/wechattweak-cli")
```
保存后，退出 Raycast，重启生效

**Comment by nscmiaoxin** [comment]
> 我修改了一下 `~/.config/raycast/extensions/cafe5af0-e733-4989-b9f1-4424f66f25bf/index.js` 的插件代码(插件id的值不确定所有人都一样，需要自己确认)，把 路径 判断给改成我机器上的了，通过 `which wechattweak-cli` 命令确认自己的 tweak 路径，我的路径是 /opt/homebrew/bin/wechattweak-cli
> 
> ```
> la.existsSync("/usr/local/bin/wechattweak-cli")
> // 从上面改成下面
> la.existsSync("/opt/homebrew/bin/wechattweak-cli")
> ```
> 
> 保存后，退出并重启 Raycast 后生效

就是这个问题，已经按照这个流程解决，ID也和你的完全一样，谢谢！

**Comment by raffeyang** [comment]
clone最新的代码，输入，测试是否正常，如果正常我会更新一下商店版本
'npm install'
`npx ray develop`

**Comment by raffeyang** [comment]
商店版本审核通过之前，可以先用这里的方法使用最新版
https://github.com/raffeyang/wechat/releases/tag/Raycast

**Comment by raffeyang** [comment]
审核通过，可以使用商店版本了
https://www.raycast.com/raffeyang/wechat
